name: flutter_multi_module_di
description: A simple and modular dependency injection system for Flutter.
version: 2.0.3
repository: https://github.com/Cilestal/flutter-multi-module-di

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  disposable_object: ^2.0.0
  flutter:
    sdk: flutter
