name: flutter_multi_module_di
description: A simple and modular dependency injection system for Flutter.
version: 1.0.0
repository: https://github.com/Cilestal/flutter-multi-module-di

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  quiver: ^2.0.1
  disposables: ^0.1.2
  flutter:
    sdk: flutter
